### ISSUE TITLE
Unable to load documentation from git project starting with "content"

### ISSUE THREAD

**Issue by sigdestad** [enonic/site-developer#127]
Just added documentation to https://github.com/enonic/app-contentstudio

Added a new "doc" entry in XP, with path /developer/docs/content-studio.

The import seems to fail when it is trying to find this page for some reason? As you can see from the error below, it has somehow constructed a path called "/developer/docs-studio", rather than /developer/docs/content-studio. The import worked fine when renaming the doc to "test-studio".

Please make this more robust, path to content should not be generated, but simply retrieved imho.

`10:16:42.455 INFO  com.enonic.site.developer - (/services/gitme/gitme.js) Docs and guides referencing repo "https://github.com/enonic/app-contentstudio" - 110:16:43.347 INFO  c.e.s.d.t.repo.GetVersionsCommand - Fetching [/docs/versions.json] from [enonic/app-contentstudio] ...10:16:43.583 INFO  c.e.s.d.t.repo.GetVersionsCommand - No [/docs/versions.json] found in [enonic/app-contentstudio]10:16:43.586 INFO  com.enonic.site.developer - (/services/gitme/gitme.js) versions: {"versions":[{"label":"master","checkout":"master","commitId":"04ba879733b7892d53e7fd561da0112bc52321bc","latest":true}]}10:16:43.983 INFO  c.e.s.d.tools.repo.CloneRepoCommand - Retrieving Git repository from [ https://github.com/enonic/app-contentstudio : master ] ...10:18:04.893 INFO  c.e.s.d.tools.repo.CloneRepoCommand - Git repository retrieved.10:18:05.274 INFO  c.e.s.d.t.imports.ImportDocCommand - Creating docversion content [master]10:18:05.275 ERROR c.e.s.d.tools.imports.ImportCommand - Failed to import data from [/enonic-xp/bin/docs-repos/enonic/app-contentstudio/docs]com.enonic.xp.content.ContentNotFoundException: Content with path [/developer/docs-studio] was not found in branch [draft]	at com.enonic.xp.core.impl.content.GetContentByPathCommand.execute(GetContentByPathCommand.java:32)	at com.enonic.xp.core.impl.content.AbstractContentCommand.getContent(AbstractContentCommand.java:61)	at com.enonic.xp.core.impl.content.CreateContentCommand.populateParentPath(CreateContentCommand.java:361)`

**Comment by ashklianko** [comment]
Updated!

**Comment by sigdestad** [comment]
Hmm.. Had a look at the change, and this still does not seem robust to me? Now, things will break if i name something "content". How about making sure the replacement only occurs at the beginning of the string, and not the whole thing instead?

**Comment by ashklianko** [comment]
Will add regex then

**Comment by sigdestad** [comment]
Also a question, are you adding data with the content API, or node level things?

**Comment by ashklianko** [comment]
Using ContentService for importing data

**Comment by ashklianko** [comment]
Updated with regex

**Comment by sigdestad** [comment]
Confirmed, tested on QA and deployed. TNX
