### ISSUE TITLE
Create new downloads/ page

### ISSUE THREAD

**Issue by sigdestad** [enonic/site-developer#134]
Replacing the old page on Enonic.com:

1. Should be in menu
2. Create sub page xp6/ with download ribbon + videos from old site
3. Contents
Enonic Downloads
Small text in the top, looking for xp6 bla bla..

Market
Info and links

Docker
Links to docker hub

CLI Latest
- Info, use brew, scoop etc /start
- Listing latest CLI binaries from repo.enonic.com

XP binary downloads
- Listing latest binary downloads from repo.enonic.com

**Comment by hjelmevold** [comment]
This issue has been solved in the sense that the new downloads page is live, although some details (e.g. a sub-page /xp6 for legacy downloads) have been solved different from the original specification. I'm setting the status of this issue to Done.
