### ISSUE TITLE
Fix "autocompletion" output for main search

### ISSUE THREAD

**Issue by sigdestad** [enonic/site-developer#138]
Current:

some title (version)
some title (version)
Some guide

Want: 

Configuration files - Enonic XP - Docs
Some guide name - Guides
Some starter name - Get started

Fint om alt etter hit tittel er litt gråere enn selve tittelen

**Comment by hjelmevold** [comment]
There are still some edge cases that can be improved, for instance when searching for "library" a number of library docs get the same name twice, e.g. "thymeleaf library - thymeleaf library - refrerence docs"

**Comment by hjelmevold** [comment]
Deployed to QA now.
