### ISSUE TITLE
Left menu in docs should scroll independent of page

### ISSUE THREAD

**Issue by RF0** [enonic/site-developer#157]
It's a bit annoying that you have close menu, decrease zoom level or to scroll to the bottom of the page to see the last items of the left site menu. It should be scrollable on its own.
F.x. https://developer.enonic.com/docs/xp/stable/cms/input-types 
<img width="686" alt="Screenshot 2019-08-01 at 10 58 32" src="https://user-images.githubusercontent.com/951293/62279955-539f3380-b44b-11e9-8d53-920ad51b715a.png">

**Comment by poi33** [comment]
This should be fixed now. 
ref: 4f1f793
