### ISSUE TITLE
Support variables in doc.

### ISSUE THREAD

**Issue by jsi** [enonic/site-developer#159]
Some special codes may need to be updated all over the doc.  At least, the version number for XP is such a code that should have a universal version-number, that will be replaced in all doc, everywhere, every time it is updated.

One example where this is needed and used to work, is this page: https://developer.enonic.com/docs/xp/stable/framework/java-bridge

The link at the bottom is not hardcoded to 7.0.2, but should be a global variable.  Another place where it will probably be natural to use such a variable is  in the Deployment part of the admin doc: https://developer.enonic.com/docs/xp/stable/deployment

We may also need version numbers available for Content Studio and Enonic CLI. 🤞

**Comment by sigdestad** [comment]
This is already in place - simly use adoc vars, and prefix the variable file with . to prevent it from being imported along with the rest of the documentation
