### ISSUE TITLE
Feature request: add feedback/improvements section to docs

### ISSUE THREAD

**Issue by thomasheartman** [enonic/site-developer#328]
## Feature

Add a little note at the bottom of each documentation page with information about where the users can go to give feedback and suggest improvements. 

The note can also suggest that users make pull requests themselves if they know what needs to be done.

## Background

As a new contributor, I don't always know where to report issues I find with missing, misleading, or inadequate documentation. Having an easily accessible way to give feedback about this available on each page would be very useful. Microsoft (docs.microsoft.com) and Mozilla (MDN) do this and I've personally taken advantage of that on a number of occassions. 

For reference, Microsoft's version looks like this:

![Microsoft feedback note](https://user-images.githubusercontent.com/17786332/110753250-a73c4a80-8246-11eb-935a-d800af144c30.png)

and Mozilla's version like this:

![MDN feedback note](https://user-images.githubusercontent.com/17786332/110753210-98559800-8246-11eb-9ce2-915558ad722d.png)

MDN's version may be a better reference point for us if we want to encourage people to contribute fixes rather than just reporting them. It also has the date for when it was last updated which is neat. This could perhaps even link to the last commit that touched the docs?

-----

This feature was also [discussed on slack](https://enonic.slack.com/archives/C1GAHTD0V/p1615386166026500n) on 2021-03-10 and the consensus was that this could be useful.

**Comment by sigdestad** [comment]
Suggestion:
Use link to "Edit this page on Github" -> Github direct link to page
Use link to "Report a problem with this page" -> Github issue (with reference to page?)
