### ISSUE TITLE
jsdoc as part of developer portal

### ISSUE THREAD

**Issue by rymsha** [enonic/site-developer#376]
continuation of https://github.com/enonic/xp/issues/7902

developer portal should host jsdocs

**Comment by rymsha** [comment]
This is not an ideal solution but good enough for now:
generate jsdocs during site-portal build

Next step would be to release developer portal app from generation any docs, so all docs get pushed to it instead.

**Comment by sigdestad** [comment]
Not sure if I follow this one, are you planning to include the jsdoc as static files within the developer portal app?

**Comment by alansemenov** [comment]
Not static. Developer portal app will built jsdoc from xp sources.
