### ISSUE TITLE
The new mounted /jsdoc only works locally

### ISSUE THREAD

**Issue by poi33** [enonic/site-developer#416]
Going to developer.enonic.com/jsdoc 
Results in: https://developer.enonic.com/site/dev-portal/master/developer/jsdoc/

And gives a 404. 
While locally going to http://localhost:8080/site/dev-portal/master/developer/jsdoc/ renders the doc pages

**Comment by thomasheartman** [comment]
This needs an XP update to be done. Currently blocked.

**Comment by poi33** [comment]
🎉 🎆
