### ISSUE TITLE
"Link list" (Links to other resources and important landing pages)

### ISSUE THREAD

**Issue by sigdestad** [enonic/site-developer#642]
Suggested design (NB! components are exclusively the buttons, no padding etc. Text is outside) - See cards component
![Screenshot 2022-02-04 at 15 23 33](https://user-images.githubusercontent.com/482228/152547015-602cd538-e75a-42f6-94a5-bffe663696d4.png)

**Comment by poi33** [comment]
Here is how the current design looks: 
![image](https://user-images.githubusercontent.com/3340349/153565753-e9a00c12-a22b-4592-8917-20c2bdda188d.png)

And mobile: 
![image](https://user-images.githubusercontent.com/3340349/153565797-4a8d073b-94a2-4f61-8360-31db4c4a8f2e.png)

**Comment by reisfmb** [comment]
First version is in [QA](https://qa.enonic.com/admin/tool/com.enonic.app.contentstudio/main#/dev-portal/edit/8817a73f-51d2-441f-97c5-d2371975d845).
